# Generated by Django 5.2.1 on 2025-05-26 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.PositiveSmallIntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2025, 5, 26, 11, 29, 3, 939883, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'otp code',
                'verbose_name_plural': 'otp code',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='myuser_groups', related_query_name='myuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='myuser_permissions', related_query_name='myuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'my users',
                'verbose_name_plural': 'my users',
            },
        ),
    ]
