# Generated by Django 5.2.1 on 2025-05-26 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 11, 29, 22, 50583, tzinfo=datetime.timezone.utc)),
        ),
    ]
