# Generated by Django 5.2.1 on 2025-05-27 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 19, 36, 17, 957260, tzinfo=datetime.timezone.utc)),
        ),
    ]
