# Generated by Django 5.2.1 on 2025-05-26 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 11, 32, 46, 515577, tzinfo=datetime.timezone.utc)),
        ),
    ]
