# Generated by Django 5.2.1 on 2025-05-27 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('short_description', models.TextField(max_length=250, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description for mobile')),
                ('inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='inventory')),
                ('price_main', models.PositiveIntegerField(verbose_name='price')),
                ('price_with_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='price with discount')),
                ('image', models.ImageField(upload_to='cover/', verbose_name='image')),
                ('is_active', models.BooleanField(verbose_name='active?')),
                ('date_time_added', models.DateTimeField(auto_now_add=True, verbose_name='date time added')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'mobile',
                'verbose_name_plural': 'mobile',
                'ordering': ['-date_time_added'],
            },
        ),
    ]
