# Generated by Django 5.2.1 on 2025-05-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='Category',
            new_name='category',
        ),
    ]
